baseURL = 'https://cloudsnooze.io/'
languageCode = 'en-us'
title = 'CloudSnooze'
theme = 'docsy'

[params]
  description = 'Automatically stop idle cloud instances to save costs'
  github_repo = 'https://github.com/scttfrdmn/cloudsnooze'
  github_project_repo = 'https://github.com/scttfrdmn/cloudsnooze'
  
  # Docsy theme parameters
  time_format_default = "Jan 2, 2006"
  time_format_blog = "Jan 2, 2006"
  
  # Logo configuration
  [params.ui]
    navbar_logo = true
    navbar_logo_color = true
    
  [params.logos]
    # Logo /images/logo.png set in assets/ will override this
    logo = "/images/cloudsnooze_logo.png"
    icon = "/favicon.png"

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = 10
    url = "/docs/"
  [[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/scttfrdmn/cloudsnooze"

# Using theme directly from themes directory, no module imports needed

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true