baseURL = 'https://scttfrdmn.github.io/cloudsnooze/'
languageCode = 'en-us'
title = 'CloudSnooze'
theme = 'docsy'

[params]
  description = 'Automatically stop idle cloud instances to save costs'
  github_repo = 'https://github.com/scttfrdmn/cloudsnooze'
  github_project_repo = 'https://github.com/scttfrdmn/cloudsnooze'
  
  # Docsy theme parameters
  time_format_default = "Jan 2, 2006"
  time_format_blog = "Jan 2, 2006"

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = 10
    url = "/docs/"
  [[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/scttfrdmn/cloudsnooze"

[module]
  [[module.imports]]
    path = 'github.com/google/docsy'

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true