name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.4'
          extended: true

      - name: Setup Hugo site
        run: |
          # Skip creating files since they're already in the repo
          echo "Hugo site structure already exists in repository"
          
          # Create themes directory and clone necessary dependencies
          mkdir -p hugo/themes
          
          # Clone Docsy theme directly into the themes directory with specific version
          git clone --depth 1 --branch v0.8.0 https://github.com/google/docsy.git hugo/themes/docsy
          
          # Clone Font-Awesome directly
          mkdir -p hugo/themes/github.com/FortAwesome
          git clone --depth 1 https://github.com/FortAwesome/Font-Awesome.git hugo/themes/github.com/FortAwesome/Font-Awesome
          
          # Clone Bootstrap directly
          mkdir -p hugo/themes/github.com/twbs
          git clone --depth 1 https://github.com/twbs/bootstrap.git hugo/themes/github.com/twbs/bootstrap
          
          # Initialize hugo modules
          cd hugo
          hugo mod init github.com/scttfrdmn/cloudsnooze/hugo || true

      - name: Build
        run: |
          # Install PostCSS for Docsy
          npm install -g postcss-cli autoprefixer
          
          # Build the site
          cd hugo
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo/public