name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Build CLI
      run: cd cli && go build -v ./...

    - name: Test CLI
      run: cd cli && go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Build Daemon
      run: cd daemon && go build -v ./...

    - name: Test Daemon
      run: cd daemon && go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload Daemon coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./daemon/coverage.txt
        flags: daemon
        fail_ci_if_error: false

    - name: Upload CLI coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cli/coverage.txt
        flags: cli
        fail_ci_if_error: false

  aws-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Run AWS integration tests
      run: cd daemon && go test -tags=integration -race -coverprofile=coverage-aws.txt -covermode=atomic ./cloud/aws

    - name: Upload AWS coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./daemon/coverage-aws.txt
        flags: aws-integration
        fail_ci_if_error: false